FROM apache/airflow:slim-3.0.2-python3.9
USER root
RUN apt-get update && apt-get install -y --no-install-recommends ffmpeg && apt-get clean && rm -rf /var/lib/apt/lists/*
USER airflow
RUN pip install --no-cache-dir psycopg2-binary asyncpg
RUN pip install --no-cache-dir boto3
RUN pip install --no-cache-dir apache-airflow-providers-cncf-kubernetes
